workflows:
  android_mvp:
    name: Android MVP
    instance_type: mac_mini_m2
    environment:
      flutter: stable

    scripts:
      - name: Prepare Android project (fresh scaffold)
        script: |
          set -e
          flutter --version
          ls -la
          # Force a clean Android app scaffold so android/app/build.gradle exists
          rm -rf android
          flutter create --platforms=android --template=app .
          echo "---- ANDROID TREE (top) ----"
          ls -la android
          echo "---- ANDROID APP (top) ----"
          ls -la android/app

      - name: Get packages
        script: flutter pub get

      - name: Build Debug APK
        script: |
          set -e
          flutter clean
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
