workflows:
  android-mvp:
    name: Android MVP
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Provide google-services.json (optional)
        script: |
          if [ -n "$GOOGLE_SERVICES_JSON_B64" ]; then
            echo "$GOOGLE_SERVICES_JSON_B64" | base64 --decode > android/app/google-services.json
            echo "google-services.json written to android/app/"
          else
            echo "No GOOGLE_SERVICES_JSON_B64 set; build may still run with dummy values."
          fi

      - name: Generate firebase_options.dart
        script: python3 scripts/gen_firebase_options.py

      - name: Build Debug APK
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
