name: human_rhythms
description: Bubble-diary routines & insights MVP
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  go_router: ^14.2.0
  intl: ^0.19.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.3
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
