import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by CI from google-services.json
import 'package:go_router/go_router.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  String? initError;
  try {
    // Initializes using values from firebase_options.dart (no Gradle plugin required)
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    initError = e.toString();
  }

  runApp(App(initError: initError));
}

class App extends StatelessWidget {
  final String? initError;
  App({super.key, this.initError});

  final _router = GoRouter(
    initialLocation: '/',
    routes: [GoRoute(path: '/', builder: (_, __) => const HomeScreen())],
  );

  @override
  Widget build(BuildContext context) {
    if (initError != null) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          appBar: AppBar(title: const Text('Init error')),
          body: SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Text(initError!, textAlign: TextAlign.left),
          ),
        ),
      );
    }
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      routerConfig: _router,
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});
  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(child: Text('Firebase OK + Router OK')),
    );
  }
}

  runApp(App(initError: initError, firebaseReady: firebaseReady));
}

class App extends StatelessWidget {
  final String? initError;
  final bool firebaseReady;
  App({super.key, this.initError, required this.firebaseReady});

  final _router = GoRouter(
    initialLocation: '/',
    routes: [ GoRoute(path: '/', builder: (_, __) => const HomeScreen()) ],
  );

  @override
  Widget build(BuildContext context) {
    if (initError != null) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          appBar: AppBar(title: const Text('Init error')),
          body: Center(child: Text(initError!, textAlign: TextAlign.center)),
        ),
      );
    }
    if (!firebaseReady) {
      return const MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          body: Center(child: Text('Firebase skipped (non-Android or missing JSON)')),
        ),
      );
    }
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      routerConfig: _router,
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});
  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(child: Text('Firebase OK + Router OK')),
    );
  }
}
