// GENERATED by scripts/gen_firebase_options.py (also committed for local/CI parity)
// Values sourced from android/app/google-services.json (project: trailer--setup)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
    apiKey: 'AIzaSyD9mNGzOqNIMjkINgDSJADDEHDXkp-bzBY',
    appId: '1:973113800356:android:86e0239dc260896bfc1831',
    messagingSenderId: '973113800356',
    projectId: 'trailer--setup',
    storageBucket: 'trailer--setup.firebasestorage.app',
  );
}
