#!/usr/bin/env python3
"""
generate_firebase_options.py

Reads google-services.json and writes lib/main/script/firebase_options.dart
with FirebaseOptions class for Flutter.
"""

import json
import os
import sys

INPUT_PATH = "android/app/google-services.json"
OUTPUT_PATH = "lib/main/script/firebase_options.dart"

def main():
    if not os.path.exists(INPUT_PATH):
        print(f"[ERROR] {INPUT_PATH} not found. Exiting.", file=sys.stderr)
        sys.exit(1)

    with open(INPUT_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    project_info = data.get("project_info", {}) or {}
    project_id = project_info.get("project_id", "")
    project_number = project_info.get("project_number", "")
    storage_bucket = project_info.get("storage_bucket", "")

    client = (data.get("client") or [{}])[0]
    client_info = client.get("client_info", {}) or {}
    app_id = client_info.get("mobilesdk_app_id", "")

    api_key_info = (client.get("api_key") or [{}])[0]
    api_key = api_key_info.get("current_key", "")

    dart_code = f"""// GENERATED BY generate_firebase_options.py
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {{
  static FirebaseOptions get currentPlatform {{
    return const FirebaseOptions(
      apiKey: '{api_key}',
      appId: '{app_id}',
      messagingSenderId: '{project_number}',
      projectId: '{project_id}',
      storageBucket: '{storage_bucket}',
    );
  }}
}}
"""

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as out:
        out.write(dart_code)

    print(f"[OK] Wrote {OUTPUT_PATH}")

if __name__ == "__main__":
    main()

